### ISSUE TITLE
New-PowerAutomateDoc.ps1 will fail if flow only contains 1 action

### ISSUE THREAD

**Issue by acieslik** [stefanstranger/logicappdocs#11]
If the flow only contains one action, the $Actions variable in the Sort-Action function will not be an array and thus has no Count property.

Sort-Action : The property 'Count' cannot be found on this object. Verify that the property exists.
At C:\Repos\github\logicappdocs\src\New-PowerAutomateDoc.ps1:195 char:1
+ Sort-Action -Actions $objects
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Sort-Action], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Sort-Action

**Comment by stefanstranger** [comment]
Fixed the issue, will be part of next release.
