### ISSUE TITLE
Get-Flow is not returning all flows => replace with Get-AdminFlow

### ISSUE THREAD

**Issue by acieslik** [stefanstranger/logicappdocs#12]
Even with the Top-parameter I cannot find many of my flows in the environment.
The evironment has a few hundred flows.

The only way to find these is to replace Get-Flow with Get-AdminFlow which uses paging internally and allows us to find any flow:

`Get-AdminFlow -EnvironmentName $EnvironmentName -Filter $PowerAutomateName -OutVariable PowerAutomateFlow
$PowerAutomateFlow = $PowerAutomateFlow[0]`

**Comment by stefanstranger** [comment]
Hi @acieslik,

Thanks for your feedback. So because I used 👇

```powershell
#region login to Power Automate and get PowerAutomate Flow
Write-Host ('Login to Power Automate and get PowerAutomate Flow') -ForegroundColor Green
Get-Flow -EnvironmentName $EnvironmentName | Where-Object { $_.DisplayName -eq $PowerAutomateName } -OutVariable PowerAutomateFlow
#endregion
```
The Where-Object logic prevents you from finding the right flow due to the large number of flows you have in your environment?

My environment does not have that many flows, so that's why I didn't see this issue. Let me investigate your suggestion.

Regards,
Stefan

**Comment by stefanstranger** [comment]
When I try to use in my tenant your suggestion:

```PowerShell
#region login to Power Automate and get PowerAutomate Flow
Write-Host ('Login to Power Automate and get PowerAutomate Flow') -ForegroundColor Green
Get-AdminFlow -EnvironmentName $EnvironmentName -Filter $PowerAutomateName -OutVariable PowerAutomateFlow 
#Get-Flow -EnvironmentName $EnvironmentName | Where-Object { $_.DisplayName -eq $PowerAutomateName } -OutVariable PowerAutomateFlow
#endregion
```

I get a forbidden error, so I don't think we should follow this idea. I need to think about adding paging to the Get-Flow function.

**Comment by stefanstranger** [comment]
@acieslik Can you try the following:

```PowerShell
$EnvironmentId = <enter environmentid>
$Token = Get-JwtToken -Audience 'https://service.powerapps.com'

$headers = @{}
$headers.Add("Accept", "*/*")
$headers.Add("Authorization", "Bearer $token")

$reqUrl = ('https://preview.api.flow.microsoft.com/providers/Microsoft.ProcessSimple/environments/{0}/flows?$filter=search(%27personal%27)&$top=50&include=includeSolutionCloudFlows&api-version=2016-11-01' -f $environmentId)

$response = Invoke-RestMethod -Uri $reqUrl -Method Get -Headers $headers  
$response | ConvertTo-Json
```

And tweak the filter in such a way that it works for you and share that back to me?

/Stefan

**Comment by acieslik** [comment]
Hi @stefanstranger,

I tried it out, but I have to say, that this endpoint looks not very reliable for my use case in selecting and documenting any flow that exists in my environment. My user role for D365 is  Sys. Admin. and I also have the Power Platform Administrator role.

When I open the Default solution in our productive environment I can see and open 437 Cloud Flows. My goal would be to somehow document any or as much as possible of them.

Using the suggested endpoint I can only retrieve 46 flows, which is far from the total number of 437, no matter if I increase the TOP flag to 1000 or leave it out completely and no matter if I use $filter=all or not.

With Get-AdminFlow I get back up to 387 flows. The rest or gap are OOTB standard Microsoft flows.
In our Enterprise environment our flows are usually assigned to technical users as being the owner, except for some cases, where its necessary to run for a certain business unit or user.

Maybe it makes sense to create a separate New-AdminPowerAutomateDoc.ps1 version to cover my use case?

Andreas

**Comment by acieslik** [comment]
Hi @stefanstranger,
OK, then I would go ahead and create a fork and continue to implement the "Admin" version there.
Andreas
