### ISSUE TITLE
Create-ExportPackage : The property 'connectionReferences' cannot be found on this object

### ISSUE THREAD

**Issue by acieslik** [stefanstranger/logicappdocs#15]
I have multiple flows that somehow do not have a connection reference.
This is why the doc generation will fail in line 87/88:

`$body = @{
        includedResourceIds = @(
            "/providers/Microsoft.Flow/flows/$($flow.FlowName)"
            $flow.Internal.properties.connectionReferences.PSObject.Properties.value.id
            $flow.Internal.properties.connectionReferences.PSObject.Properties | Foreach-Object { $('{0}/connections/{1}' -f $($_.value.id), $($_.value.connectionName)) } 
        )`

**Comment by stefanstranger** [comment]
I'll add a check for this in the next release.

**Comment by acieslik** [comment]
I can confirm that if you leave out the two lines with connectionReferences it will work, but you cannot leave out the includeResourcesIds completely:

This works:

>     $body = @{
>         includedResourceIds = @(
>             "/providers/Microsoft.Flow/flows/$($flow.FlowName)"
>         )
>         details             = @{
>             displayName       = $flow.DisplayName
>             description       = $flow.DisplayName
>             creator           = 'logicappdocs'
>             sourceEnvironment = $flow.EnvironmentName
>         }

**Comment by stefanstranger** [comment]
I added you suggestion in my development branch.
