### ISSUE TITLE
Get-Action : Cannot bind argument to parameter 'Inputs' because it is null

### ISSUE THREAD

**Issue by acieslik** [stefanstranger/logicappdocs#16]
I have a flow that is using a **Switch** block and does not contain an inputs value:
![2023-08-09 14_29_28-InputsNull1](https://github.com/stefanstranger/logicappdocs/assets/3213497/26b3e02c-cbe1-4983-97dd-6af0e6723d1f)
Then in the Helper.ps1:
`        $inputs = if ($action | Get-Member -MemberType Noteproperty -Name 'inputs') { 
            $($action.inputs)
        } 
        else { 
            $null 
        }`
$inputs becomes $null
and later it will crash here...
![2023-08-09 14_29_28-InputsNull2](https://github.com/stefanstranger/logicappdocs/assets/3213497/0f610c1d-0157-4fdf-9d78-ef773ae16f71)
with error:
Get-Action : Cannot bind argument to parameter 'Inputs' because it is null.
At C:\Repos\github\logicappdocs\src\New-PowerAutomateDoc.ps1:137 char:12
\+  ´$Objects= Get-Action -Actions $($PowerAutomateFlowJson.properties.de´ ...
\+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
\+     CategoryInfo          : InvalidData: (:) [Get-Action], ParameterBindingValidationException
\+     FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Get-Action

**Comment by stefanstranger** [comment]
Hi @acieslik,

Thanks for sharing this issue. Fixed this with the following in branch called powerautomateissues

Helper.ps1 script
```powershell
# Create PSCustomObject
        [PSCustomObject]@{
            ActionName   = $actionName
            RunAfter     = $runAfter
            Type         = $type
            Parent       = $Parent
            ChildActions = $childActions
            Inputs       = if ($inputs) {Format-HTMLInputContent -Inputs $(Remove-Secrets -Inputs $($inputs | ConvertTo-Json -Depth 10 -Compress))} else {$null}
        }
```

**Comment by acieslik** [comment]
I cannot see that change in any available branch. Am I missing out something?

**Comment by stefanstranger** [comment]
I still need to push my local development branch.
