### ISSUE TITLE
The string is missing the terminator: "@.

### ISSUE THREAD

**Issue by pete076** [stefanstranger/logicappdocs#18]
When I run your script I get the following error:

![image](https://github.com/stefanstranger/logicappdocs/assets/98805974/a401cd7a-1a47-49cc-9aa7-880febdb7843)

After al little bit of digging, when i remove this part from  'LogicAp.Doc.ps1' the script runs fine but no graphic is embedded in the resulting .md file

![image](https://github.com/stefanstranger/logicappdocs/assets/98805974/0989e617-58e2-4503-8dcc-f1b03d95030c)

How can this be solved?

**Comment by stefanstranger** [comment]
Hi @pete076 

Can you enable verbose logging and share the verbose output too? Just add at the end -verbose

**Comment by pete076** [comment]
Mermaid code is generated well.

[verbose logfile.txt](https://github.com/stefanstranger/logicappdocs/files/12313396/verbose.logfile.txt)
[content mermaid.txt](https://github.com/stefanstranger/logicappdocs/files/12313460/content.mermaid.txt)

Im running this within VSCode version 1.81
PowerShell Extension v2023.6.0

It make no different if I run this outside VSCode

**Comment by stefanstranger** [comment]
I meant the version of logicappsdoc 😁

**Comment by pete076** [comment]
Author: Stefan Stranger
Github: https://github.com/stefanstranger/logicappdocs
Version: 1.1.0

Main branche, downloaded today

**Comment by stefanstranger** [comment]
Hi @pete076 ,

When I look at the LogicApp.Doc.ps1 script on lines 24 till 28 I see that it there is a here string configured.

```PowerShell
        @"        
```````mermaid
$($InputObject.diagram)
```````
"@
```

It contains 7 backtic's at the moment and you are saying it needs to be 6 and then it works for you?

Strange because this has not given me any errors until now. Let me validate this.

Regards,
Stefan

**Comment by stefanstranger** [comment]
After testing with 6 backtics it works fine. Fixed in development branch powerautomatissues. Will be available in next release.
