### ISSUE TITLE
-OutputPath has no default or is not mandatory, causing error when script is ran with no params

### ISSUE THREAD

**Issue by three-kings-code** [stefanstranger/logicappdocs#2]
When running the script without any params on the command line, you are not prompted for -OutputPath therefore when the script gets to line 406 in the code it completes but does not save the markdown file to a location and then line 407 fails as there is no .FullName for the command to reference as shown below

New-LogicAppDoc.ps1: The property 'FullName' cannot be found on this object. Verify that the property exists.

Easy Solution is to make the -OutPath Mandatory

    [Parameter(Mandatory = $true)]
    [string]$OutputPath

Other solution is to set the -Outpath as current directory and leave it as not Mandatory

    [Parameter(Mandatory = $false)]
    [string]$OutputPath = (Get-Location).Path

**Comment by stefanstranger** [comment]
Hi @three-kings-code,

Thanks for bringing up this issue and the possible solutions! I choose option 2 and fixed the issue.

Regards,
Stefan Stranger

**Comment by stefanstranger** [comment]
Hi @three-kings-code,

Thanks for bringing up this issue and the possible solutions! I choose option 2 and fixed the issue.

Regards,
Stefan Stranger
