### ISSUE TITLE
Multiple 'RunAfter' statements for a single action fails to produce valid mermaid code

### ISSUE THREAD

**Issue by SjoerdV** [stefanstranger/logicappdocs#23]
**Describe the bug**
One action called `Send_email` in a LA has the following code
```
"runAfter": {
	"CalculateDigest": [
    	"Succeeded"
	],
	"Compose_2": [
    	"Succeeded"
	],
	"HTTP": [
    	"Succeeded"
	]
}
```
This will lead to a mermaid construct as follows
```
CalculateDigest Compose_2 HTTP --> Send_email
```
This will fail to render

**Add error message**
```
Parse error on line 7:
...CalculateDigest Compose_2 HTTP --> S
---------------^
Expecting 'SEMI', 'NEWLINE', 'EOF', 'AMP', 'START_LINK', 'LINK', got 'ALPHA'
```

**Expected behavior**
Multiple `runAfter` statements should be parsed to mermaid as follows:
```
CalculateDigest --> Send_email
Compose_2 --> Send_email
HTTP --> Send_email
```

**Screenshots**
NA

**PowerShell version:**
Run $PSVersionTable command in PowerShell host
e.g.
```PowerShelll
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Linux
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
**LogicAppDocs version**
 - Version 1.1.1

**Additional context**
NA

**Comment by stefanstranger** [comment]
Hi @SjoerdV,

Thanks for sharing this issue with me. Would it be possible to share the complete Log Analytics of PowerAutomate Flow code with me, so I can test this? 

If so please remove any sensitive content. This can also be shared using a secret gist if you prefer. 

https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists

**Comment by SjoerdV** [comment]
I'll do you one better. The actual piece of code that needs adjustment is here: https://github.com/stefanstranger/logicappdocs/blob/91c6622c40c3a8e58df1325dccfd075b4a663a0b/src/New-LogicAppDoc.ps1#L192-L200

Needs a `foreach` to account for multiple `runAfter` keys.

example:

```powershell
# Example Data
$runAfterObj = @'                    
{
    "runAfter": {
        "CalculateDigest": ["Succeeded"],
        "Compose_2": ["Succeeded"],
        "HTTP": ["Succeeded"]
    }
}
'@ | ConvertFrom-Json -AsHashtable

# Modified code
foreach ($Key in $runAfterObj.runAfter.Keys) {
  $mermaidCode += "    $($Key) --> $($object.ActionName)" + [Environment]::NewLine
}
```

**Comment by stefanstranger** [comment]
Hi @SjoerdV ,

Thanks for the help and code🙏Let me find some time to update the code in the main branch.

**Comment by SjoerdV** [comment]
@stefanstranger works like a charm! I tested both single and multiple `runafter` constructs.
Great work building this.

**Comment by stefanstranger** [comment]
Merged changes into main branch. Closing issue.
