### ISSUE TITLE
$currentAction.Parent could be $null, length property will then fail

### ISSUE THREAD

**Issue by acieslik** [stefanstranger/logicappdocs#25]
https://github.com/stefanstranger/logicappdocs/blob/40dc946abdc6531a1df426180527323553b8ed99/src/Helper.ps1#L172-L173

line 173 should be replaced with:
`                elseif (($null -ne $currentAction.Parent) -and ($Actions | Where-Object { $_.RunAfter -eq $(('{0}-False') -f $(($currentAction.Parent).Substring(0, ($currentAction.Parent).length - 5))) } )) {
`

**Comment by stefanstranger** [comment]
Hi @acieslik,

Sorry for not responding earlier. I was a bit busy and on holiday. Hope to find some time next weeks. 

/Stefan

**Comment by stefanstranger** [comment]
Finally found time to create PR and fix this issue. So sorry @acieslik that it took this long to close this issue.
