### ISSUE TITLE
The property '$connections' cannot be found on this object

### ISSUE THREAD

**Issue by acieslik** [stefanstranger/logicappdocs#6]
Before calling...

Line 325:
`$Connections = Get-Connection -Connection $($LogicApp.properties.parameters.'$connections'.value)`
or
Line 334:
`$Connections = Get-Connection -Connection $($LogicApp.parameters.'$connections'.value)`

it needs to be checked, if this property even exits, otherwise the script will fail with:
_**The property '$connections' cannot be found on this object. Verify that the property exists.**_

**Comment by acieslik** [comment]
![image](https://github.com/stefanstranger/logicappdocs/assets/3213497/348ed3f1-dcf9-4bbe-ad34-35fc94c98ece)
I fixed it like this, maybe there are better options

**Comment by stefanstranger** [comment]
Let me have a look at this issue. Just to be clear, you have a flow without any connections?

**Comment by acieslik** [comment]
Yes, its a logic app that triggers on "When a HTTP request is received" and itself will only use an HTTP action, check the results and returns a proper HTTP response. So for such use cases connections are not required.

**Comment by stefanstranger** [comment]
Hi @acieslik,

I made some changes to the solution and also fixed the issue when no connections are configured. Can you please download the latest version via:

```batch
git pull main
```
And let me know if this fixed the issue?

Regards,
Stefan Stranger

**Comment by acieslik** [comment]
Now it works just fine. Thanks!
